experiment:
  name: debug
  save_checkpoint_every: 1000
  save_checkpoint_every_wlong: 200
  n_epochs: 20000000
  use_writer: True
  n_steps_only_short: 50000
  enable_attractions: False
  initial_ts: 3.333333333333333e-1
  regular_ts: 3.333333333333333e-2
  max_iter: 56000

runner:
  ccraft:
    warmup_steps: 100
    increase_roll_every: 5000
    roll_max: 20
    push_eps: 2e-3
    grad_clip: 1.
    nocollect_after: 2
    no_world_edges_every: 2
    always_fake_icontour: True
    use_safecheck: True
    optimizer:
      lr: 5e-5
      decay_steps: 50_000
      decay_rate: 5e-1
    material:
      lame_mu_min: 15909
      lame_mu_max: 63636
      lame_lambda_min: 3535.414406069427
      lame_lambda_max: 93333.73508005822
      bending_coeff_min: 6.370782056371576e-08
      bending_coeff_max: 0.0013139737991266374
      density_min: 4.34e-2
      density_max: 7e-1
    safecheck:
      max_riz_size: 30
      n_rest2pos_steps: 10
      max_impulse_norm: 5e-2
      max_ncoll: 2000
      riz_epsilon: 0

dataloaders:
  short:
    num_workers: 0
    batch_size: 1
    dataset:
      ccraft:
        data_root: ''
        body_model_root: 'body_models'
        sequence_loader: 'cmu_npz_smpl'
        garment_dicts_dir: 'garment_dicts/smpl'
        obstacle_dict_file: 'smpl_aux.pkl'
        split_path: 'datasplits/train_ccraft.csv'
        pinned_verts: True
        random_betas: True
        betas_scale: 3.
        n_coarse_levels: 4
        separate_arms: True
        wholeseq: False
        lookup_steps: 20
        nobody_freq: 0.5

  long:
    copy_from: short
    dataset:
      ccraft:
        wholeseq: True
        noise_scale: 0.

criterions:
  postcvpr.mataug.stretching_energy:
  postcvpr.mataug.bending_energy:
  postcvpr.inertia:
  postcvpr.gravitational_energy:
    z_axis: 1
  ccraft.collision_penalty: #-
    weight_start: 5e+3
    weight_max: 1e+6
    eps: 3e-3
    start_rampup_iteration: 30000
    n_rampup_iterations: 10000
  ccraft.repulsion_loss: #-
    weight_start: 0.
    weight_max: 2e+6
    step_start: 30000
    step_max: 40000
    correspondence_eps: 1e-2
    penalty_eps: 3e-3
    pinned_relative_weight: 1e2

model:
  ccraft:
    core_model: 'ccraft'
    architecture: "f,c3|f,c3|f,c3|f,c3|f,c3|f,c3|f,c3|f,c3|f,c3|f,c3|f,c3|f,c3|f,c3|f,c3|f,c3"
    collision_radius: 3e-2
    body_collision_radius: 3e-2
    n_coarse_levels: 4
    allrep: True

checkpoints_dir: 'trained_models/new_training/stage1/'
device: 'cuda:0'